#!/bin/bash

#SBATCH -J cpujob
#SBATCH -A COSGROVE-SL3-CPU
#SBATCH -p icelake
#SBATCH --nodes=1
#SBATCH --ntasks=76
#SBATCH --time=01:30:00
#SBATCH --mail-type=ALL
##SBATCH --no-requeue

numnodes=$SLURM_JOB_NUM_NODES
numtasks=$SLURM_NTASKS
mpi_tasks_per_node=$(echo "$SLURM_TASKS_PER_NODE" | sed -e  's/^\([0-9][0-9]*\).*$/\1/')

. /etc/profile.d/modules.sh
module purge
module load rhel7/default-ccl

# Application executable path
application="../../Build/scone.out"

# List of files to run with the application
files=(
    "BW_fine_P1"
)

workdir="$SLURM_SUBMIT_DIR"
export OMP_NUM_THREADS=1 
np=$[${numnodes}*${mpi_tasks_per_node}]

export I_MPI_PIN_DOMAIN=omp:compact
export I_MPI_PIN_ORDER=scatter

cd ../../
sh ./build_script

cd $workdir
echo -e "Changed directory to `pwd`.\n"
JOBID=$SLURM_JOB_ID
echo -e "JobID: $JOBID\n======"
echo "Time: `date`"
echo "Running on master node: `hostname`"
echo "Current directory: `pwd`"

if [ "$SLURM_JOB_NODELIST" ]; then
    export NODEFILE=`generate_pbs_nodefile`
    cat $NODEFILE | uniq > machine.file.$JOBID
    echo -e "\nNodes allocated:\n================"
    echo `cat machine.file.$JOBID | sed -e 's/\..*$//g'`
fi

echo -e "\nnumtasks=$numtasks, numnodes=$numnodes, mpi_tasks_per_node=$mpi_tasks_per_node (OMP_NUM_THREADS=$OMP_NUM_THREADS)"

# Loop through each file and execute the application twice
for file in "${files[@]}"; do
    for run_number in 2; do #changeto123
        # Make a backup of the file
        #cp "$file" "$file.bak"

        # Replace the line starting with "outputFile" with the new desired output line
        sed -i "/^outputFile/c\outputFile ${file}_run${run_number};" "$file"

        options="--omp $numtasks"
        CMD="$application $file $options"

        echo -e "\nExecuting command for $file, run $run_number:\n==================\n$CMD\n"
        eval $CMD

        # Restore the original file from backup
        #mv "$file.bak" "$file"
    done
done
